#!/usr/bin/python
#Transforms to lab format
import sys
import re
import itertools

def main():
    usage = 'Usage: ./replace_phonemes.py in.lab out.lab full/mono'
    if len(sys.argv) != 4:
        print usage
        exit()
    in_lab = sys.argv[1]
    out_lab = sys.argv[2]
    is_full = sys.argv[3]

    ilab = open(in_lab,'r')
    olab = open(out_lab,'w')
    width = 8
    for line1 in ilab:
       	tokens = line1.split()
       	if is_full:
       		key_chars = ['-', '+','=','@']
       		phones = []
       		tokens = tokens[2].split('^')
       		phones.append(tokens[0])
       		for key in key_chars:
	       		tokens = tokens[1].split(key)
	       		phones.append(tokens[0])
	       	
	       	new_phone = []
	       	for phone in phones:
	       		if phones == '#':
	       			new_phone.append('space')
	       		else:
	       			new_phone.append(phones)
    		olab.write(new_phone[0] + '^' + new_phone[1] + '-' + new_phone[2] + '+' + new_phone[3] + '=' + new_phone[4] + "@" + line1.split('@')[1])

if __name__ == "__main__":
    main()